version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: novitas-postgres
    environment:
      POSTGRES_DB: novitas
      POSTGRES_USER: novitas
      POSTGRES_PASSWORD: novitas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novitas -d novitas"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: novitas-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  novitas:
    build: .
    container_name: novitas-app
    environment:
      - DATABASE_URL=postgresql+asyncpg://novitas:novitas@postgres:5432/novitas
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["uv", "run", "novitas", "improve", "--daily"]

volumes:
  postgres_data:
  redis_data:
