"""Initial database schema

Revision ID: d15e3dac73c5
Revises:
Create Date: 2025-08-28 14:09:05.653045

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "d15e3dac73c5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_actions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("details", sqlite.JSON(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("success", sa.String(length=10), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_states",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "agent_type",
            sa.Enum(
                "ORCHESTRATOR",
                "CODE_AGENT",
                "TEST_AGENT",
                "DOCUMENTATION_AGENT",
                name="agenttype",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "RETIRED", "ARCHIVED", name="agentstatus"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("memory", sqlite.JSON(), nullable=False),
        sa.Column("performance_metrics", sqlite.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_active", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "change_proposals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column(
            "improvement_type",
            sa.Enum(
                "CODE_IMPROVEMENT",
                "TEST_IMPROVEMENT",
                "DOCUMENTATION_IMPROVEMENT",
                "PROMPT_IMPROVEMENT",
                "CONFIG_IMPROVEMENT",
                name="improvementtype",
            ),
            nullable=False,
        ),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("proposed_changes", sqlite.JSON(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "improvement_cycles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cycle_number", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("agents_used", sqlite.JSON(), nullable=False),
        sa.Column("changes_proposed", sqlite.JSON(), nullable=False),
        sa.Column("changes_accepted", sqlite.JSON(), nullable=False),
        sa.Column("success", sa.String(length=10), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompt_templates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "agent_type",
            sa.Enum(
                "ORCHESTRATOR",
                "CODE_AGENT",
                "TEST_AGENT",
                "DOCUMENTATION_AGENT",
                name="agenttype",
            ),
            nullable=False,
        ),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prompt_templates")
    op.drop_table("improvement_cycles")
    op.drop_table("change_proposals")
    op.drop_table("agent_states")
    op.drop_table("agent_actions")
    # ### end Alembic commands ###
