name: Daily Self-Improvement

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  self-improve:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Set up database
      run: |
        docker-compose up -d postgres redis
        sleep 10  # Wait for services to be ready
    
    - name: Run database migrations
      run: uv run novitas db migrate
    
    - name: Run self-improvement cycle
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: uv run novitas improve --daily
    
    - name: Create Pull Request
      if: success()
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "🤖 Daily self-improvement cycle"
        title: "🤖 Daily Self-Improvement - $(date +%Y-%m-%d)"
        body: |
          ## 🤖 Daily Self-Improvement Cycle
          
          This PR contains the results of today's autonomous self-improvement cycle.
          
          ### Changes Made:
          - [Changes will be listed here by the AI system]
          
          ### Reasoning:
          - [AI reasoning will be documented here]
          
          ### Quality Checks:
          - [ ] All tests pass
          - [ ] Code coverage maintained
          - [ ] Documentation updated
          - [ ] Linting passes
          
          ---
          *This PR was automatically generated by the Novitas AI system.*
        branch: daily-improvement/$(date +%Y-%m-%d)
        base: main
        delete-branch: true
        labels: |
          auto-generated
          daily-improvement
          ai-generated
